// <auto-generated />
using System;
using BildiriKitabi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BildiriKitabi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928125204_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BildiriKitabi.Core.Books.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("OlusturulmaZamani")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SilinmeZamani");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HataKodu");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("HataMesaji");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("AktifMi");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Ad");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int")
                        .HasColumnName("SayfaSayisi");

                    b.Property<long?>("PdfSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("PdfBoyutuBayt");

                    b.Property<string>("PdfStorageKey")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)")
                        .HasColumnName("PdfDepolamaAnahtari");

                    b.Property<DateTime?>("ProcessingFinishedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("IslemBitisZamani");

                    b.Property<DateTime?>("ProcessingStartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("IslemBaslangicZamani");

                    b.Property<byte>("ProgressPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("IlerlemeYuzdesi");

                    b.Property<DateTime?>("QueuedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("KuyrugaAlinmaZamani");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("SatirVersiyonu");

                    b.Property<string>("Stage")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Asama");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Durum");

                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Uid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_Kitaplar_OlusturulmaZamani");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Kitaplar_Durum");

                    b.HasIndex("Uid")
                        .IsUnique()
                        .HasDatabaseName("UX_Kitaplar_Uid");

                    b.ToTable("Kitaplar", null, t =>
                        {
                            t.HasCheckConstraint("CK_Kitaplar_Basarisiz_Mesaj", "[Durum] <> 'Failed' OR [HataMesaji] IS NOT NULL");

                            t.HasCheckConstraint("CK_Kitaplar_Durum", "[Durum] IN ('Uploaded', 'Queued', 'Processing', 'Completed', 'Failed')");

                            t.HasCheckConstraint("CK_Kitaplar_IlerlemeYuzdesi", "[IlerlemeYuzdesi] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Kitaplar_Silinme", "([AktifMi] = 1 AND [SilinmeZamani] IS NULL) OR ([AktifMi] = 0 AND [SilinmeZamani] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Kitaplar_Tamamlandi_Pdf", "[Durum] <> 'Completed' OR [PdfDepolamaAnahtari] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("BildiriKitabi.Core.Books.Paper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("KitapId");

                    b.Property<int?>("EndPage")
                        .HasColumnType("int")
                        .HasColumnName("BitisSayfasi");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("SiraNo");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("OrijinalDosyaAdi");

                    b.Property<int>("RemovedEmailCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("SilinenEpostaSayisi");

                    b.Property<int>("RemovedPhoneCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("SilinenTelefonSayisi");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)")
                        .HasColumnName("Sha256")
                        .IsFixedLength();

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("DosyaBoyutuBayt");

                    b.Property<int?>("StartPage")
                        .HasColumnType("int")
                        .HasColumnName("BaslangicSayfasi");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)")
                        .HasColumnName("DepolamaAnahtari");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Baslik");

                    b.Property<string>("TitleSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("BaslikKaynagi");

                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Uid");

                    b.Property<int>("UploadOrder")
                        .HasColumnType("int")
                        .HasColumnName("YuklemeSirasi");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("YuklenmeZamani");

                    b.HasKey("Id");

                    b.HasIndex("Uid")
                        .IsUnique()
                        .HasDatabaseName("UX_Bildiriler_Uid");

                    b.HasIndex("BookId", "Order")
                        .IsUnique()
                        .HasDatabaseName("UX_Bildiriler_KitapId_SiraNo");

                    b.HasIndex("BookId", "Sha256")
                        .IsUnique()
                        .HasDatabaseName("UX_Bildiriler_KitapId_Sha256");

                    b.ToTable("Bildiriler", null, t =>
                        {
                            t.HasCheckConstraint("CK_Bildiriler_SiraNo", "[SiraNo] >= 1");

                            t.HasCheckConstraint("CK_Bildiriler_YuklemeSirasi", "[YuklemeSirasi] >= 1");
                        });
                });

            modelBuilder.Entity("BildiriKitabi.Core.Books.Paper", b =>
                {
                    b.HasOne("BildiriKitabi.Core.Books.Book", "Book")
                        .WithMany("Papers")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BildiriKitabi.Core.Books.Book", b =>
                {
                    b.Navigation("Papers");
                });
#pragma warning restore 612, 618
        }
    }
}
