/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/books': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PagedResultOfBookSummaryDto'];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'multipart/form-data': {
            name?: string;
            files?: components['schemas']['IFormFile'][];
          };
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BookDetailDto'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': components['schemas']['ProblemResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/books/deleted': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PagedResultOfDeletedBookSummaryDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/books/{uid}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          uid: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BookDetailDto'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': components['schemas']['ProblemResponse'];
          };
        };
      };
    };
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          uid: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['RenameBookRequest'];
          'application/*+json': components['schemas']['RenameBookRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BookDetailDto'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': components['schemas']['ProblemResponse'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': components['schemas']['ProblemResponse'];
          };
        };
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': components['schemas']['ProblemResponse'];
          };
        };
      };
    };
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          uid: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': components['schemas']['ProblemResponse'];
          };
        };
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': components['schemas']['ProblemResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/books/{uid}/paper-order': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          uid: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['PaperOrderRequest'];
          'application/*+json': components['schemas']['PaperOrderRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BookDetailDto'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': components['schemas']['ProblemResponse'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': components['schemas']['ProblemResponse'];
          };
        };
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': components['schemas']['ProblemResponse'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/books/{uid}/generate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          uid: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Accepted */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': components['schemas']['ProblemResponse'];
          };
        };
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': components['schemas']['ProblemResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/books/{uid}/pdf': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          download?: boolean;
        };
        header?: never;
        path: {
          uid: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/pdf': components['schemas']['Stream'];
          };
        };
        /** @description Partial Content */
        206: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/pdf': components['schemas']['Stream'];
          };
        };
        /** @description Not Modified */
        304: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': components['schemas']['ProblemResponse'];
          };
        };
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': components['schemas']['ProblemResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/books/{uid}/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          uid: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': components['schemas']['ProblemResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/books/{uid}/papers/{paperUid}/title': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          uid: string;
          paperUid: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['PaperTitleRequest'];
          'application/*+json': components['schemas']['PaperTitleRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BookDetailDto'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': components['schemas']['ProblemResponse'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': components['schemas']['ProblemResponse'];
          };
        };
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': components['schemas']['ProblemResponse'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ApiError: {
      code: string;
      message: string;
      field?: null | string;
      fileName?: null | string;
    };
    BookDetailDto: {
      /** Format: uuid */
      uid: string;
      name: string;
      status: components['schemas']['BookStatus'];
      stage: null | components['schemas']['GenerationStage'];
      /** Format: int32 */
      progressPercent: number;
      error: null | components['schemas']['BookErrorDto'];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      processingStartedAt: null | string;
      /** Format: date-time */
      processingFinishedAt: null | string;
      /** Format: int32 */
      pageCount: null | number;
      /** Format: int64 */
      pdfSizeBytes: null | number;
      pdfUrl: null | string;
      papers: components['schemas']['PaperDto'][];
    };
    BookErrorDto: {
      code: string;
      message: string;
    };
    /** @enum {unknown} */
    BookStatus: 'Uploaded' | 'Queued' | 'Processing' | 'Completed' | 'Failed';
    BookSummaryDto: {
      /** Format: uuid */
      uid: string;
      name: string;
      status: components['schemas']['BookStatus'];
      stage: null | components['schemas']['GenerationStage'];
      /** Format: int32 */
      progressPercent: number;
      /** Format: int32 */
      paperCount: number;
      /** Format: int32 */
      pageCount: null | number;
      error: null | components['schemas']['BookErrorDto'];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      processingFinishedAt: null | string;
      pdfUrl: null | string;
    };
    DeletedBookSummaryDto: {
      /** Format: uuid */
      uid: string;
      name: string;
      status: components['schemas']['BookStatus'];
      stage: null | components['schemas']['GenerationStage'];
      /** Format: int32 */
      progressPercent: number;
      /** Format: int32 */
      paperCount: number;
      /** Format: int32 */
      pageCount: null | number;
      error: null | components['schemas']['BookErrorDto'];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      processingFinishedAt: null | string;
      pdfUrl: null | string;
      /** Format: date-time */
      deletedAt: string;
    };
    /** @enum {unknown} */
    GenerationStage: 'Reading' | 'Sanitizing' | 'Composing' | 'Rendering' | 'Verifying' | 'Saving' | null;
    /** Format: binary */
    IFormFile: string;
    PagedResultOfBookSummaryDto: {
      items: components['schemas']['BookSummaryDto'][];
      /** Format: int32 */
      page: number;
      /** Format: int32 */
      pageSize: number;
      /** Format: int32 */
      totalCount: number;
    };
    PagedResultOfDeletedBookSummaryDto: {
      items: components['schemas']['DeletedBookSummaryDto'][];
      /** Format: int32 */
      page: number;
      /** Format: int32 */
      pageSize: number;
      /** Format: int32 */
      totalCount: number;
    };
    PaperDto: {
      /** Format: uuid */
      uid: string;
      /** Format: int32 */
      order: number;
      /** Format: int32 */
      uploadOrder: number;
      fileName: string;
      title: string;
      titleSource: components['schemas']['TitleSource'];
      /** Format: int32 */
      startPage: null | number;
      /** Format: int32 */
      endPage: null | number;
      /** Format: int32 */
      removedEmailCount: number;
      /** Format: int32 */
      removedPhoneCount: number;
      /** Format: int64 */
      sizeBytes: number;
    };
    PaperOrderRequest: {
      paperUids: string[];
    };
    PaperTitleRequest: {
      title: null | string;
    };
    ProblemResponse: {
      type?: null | string;
      title: string;
      /** Format: int32 */
      status: number;
      detail: string;
      code: string;
      traceId?: null | string;
      errors?: null | components['schemas']['ApiError'][];
    };
    RenameBookRequest: {
      name: null | string;
    };
    /** Format: binary */
    Stream: string;
    /** @enum {unknown} */
    TitleSource: 'TitleStyle' | 'FirstBoldParagraph' | 'FileName' | 'Manual';
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
