<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="PdfPig" />
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BildiriKitabi.Core\BildiriKitabi.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Fonts\*.ttf" LogicalName="BildiriKitabi.Fonts.%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BildiriKitabi.UnitTests" />
    <InternalsVisibleTo Include="BildiriKitabi.IntegrationTests" />
  </ItemGroup>

</Project>
