<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="PdfPig" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BildiriKitabi.Core\BildiriKitabi.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BildiriKitabi.UnitTests" />
    <InternalsVisibleTo Include="BildiriKitabi.IntegrationTests" />
  </ItemGroup>

</Project>
