<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Shared\**\*.cs" LinkBase="Shared" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BildiriKitabi.Infrastructure\BildiriKitabi.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\BildiriKitabi.Api\BildiriKitabi.Api.csproj" />
  </ItemGroup>

</Project>
